# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80e59cbe089fe60f86db8f1d3e29b050f89178e95167a342803bde86a3a167cf6d4c7cc3ac4fa6c812b03e5f29803f928bc0bd40deee2561f8ca423194112eb7

test:
  secret_key_base: 38ceeb95c45245059b71b1b95cd52ad40fa0def1451b2588a14e56dedaf9b77efc56e66f1fa34b9272dbc12fc84c605a643147d9185657f42b5767fb3cb9ad66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
